<?xml version="1.0" ?>
<robot name='robot' xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:include filename="$(find robot_description)/urdf/gazebo.urdf.xacro" />
    <xacro:include filename="$(find robot_description)/urdf/lidar.urdf.xacro" />
    <xacro:include filename="$(find robot_description)/urdf/depth.urdf.xacro" />
    <xacro:include filename="$(find robot_description)/urdf/imu.urdf.xacro" />

 <!-- Define robot constants -->
  <xacro:property name="base_width" value="0.31"/>
  <xacro:property name="base_length" value="0.42"/>
  <xacro:property name="base_height" value="0.18"/>

  <xacro:property name="wheel_radius" value="0.10"/>
  <xacro:property name="wheel_width" value="0.04"/>
  <xacro:property name="wheel_ygap" value="0.025"/>
  <xacro:property name="wheel_zoff" value="0.05"/>
  <xacro:property name="wheel_xoff" value="0.12"/>

  <xacro:property name="caster_xoff" value="0.14"/>

  <!-- Define intertial property macros  -->
  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" izz="${(m/12) * (w*w + h*h)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0" iyy="${(m/12) * (3*r*r + h*h)}" iyz = "0" izz="${(m/2) * (r*r)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0" iyy="${(2/5) * m * (r*r)}" iyz="0.0" izz="${(2/5) * m * (r*r)}"/>
    </inertial>
  </xacro:macro>
  
  
  <!-- Properties of the head -->
  <link name="head">
    <visual>
      <geometry>
        <sphere radius="0.5"/>
      </geometry>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <sphere radius="0.5"/>
      </geometry>
    </collision>
  </link>

  <!-- Properties of the hat -->
  <link name="hat">
    <visual>
      <geometry>
        <cylinder length="0.5" radius="0.2"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.5" radius="0.2"/>
      </geometry>
    </collision>
  </link>

    <!-- Properties of the hat -->
  <link name="hat1">
    <visual>
      <geometry>
        <cylinder length="0.1" radius="0.3"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.1" radius="0.3"/>
      </geometry>
    </collision>
  </link>


  <!-- Properties of the nose -->
  <link name="nose">
    <visual>
      <geometry>
        <sphere radius="0.1"/>
      </geometry>
      <material name="red">
        <color rgba="1 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <sphere radius="0.1"/>
      </geometry>
    </collision>
  </link>

  <!-- Properties of the eyes -->
  <link name="left_eye">
    <visual>
      <geometry>
        <sphere radius="0.07"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <sphere radius="0.07"/>
      </geometry>
    </collision>
  </link>

  <link name="right_eye">
    <visual>
      <geometry>
        <sphere radius="0.07"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <sphere radius="0.07"/>
      </geometry>
    </collision>
  </link>

  <!-- Properties of the mouth -->
  <link name="mouth">
    <visual>
      <geometry>
        <cylinder length="0.1" radius="0.2"/>
      </geometry>
      <material name="red">
        <color rgba="1 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.1" radius="0.2"/>
      </geometry>
    </collision>
  </link>
  
  <!-- Properties of the ears -->
  <link name="left_ear">
    <visual>
      <geometry>
        <cylinder length="0.1" radius="0.15"/>
      </geometry>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.1" radius="0.15"/>
      </geometry>
    </collision>
  </link>

  <link name="right_ear">
    <visual>
      <geometry>
        <cylinder length="0.1" radius="0.15"/>
      </geometry>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.1" radius="0.15"/>
      </geometry>
    </collision>
  </link>

  <!-- Properties of the eyebrows -->
  <link name="left_eyebrow">
    <visual>
      <geometry>
        <box size="0.2 0.02 0.01"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.2 0.02 0.01"/>
      </geometry>
    </collision>
  </link>

  <link name="right_eyebrow">
    <visual>
      <geometry>
        <box size="0.2 0.02 0.01"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.2 0.02 0.01"/>
      </geometry>
    </collision>
  </link>

  <!-- Joints connecting the features to the head -->
  <joint name="hat1_joint" type="fixed">
    <parent link="hat"/>
    <child link="hat1"/>
    <origin xyz="0 0 -0.2" rpy="0 0 0"/>
  </joint>
  
  <joint name="hat_joint" type="fixed">
    <parent link="head"/>
    <child link="hat"/>
    <origin xyz="0 0 0.7" rpy="0 0 0"/>
  </joint>

  <joint name="nose_joint" type="fixed">
    <parent link="head"/>
    <child link="nose"/>
    <origin xyz="0.5 0 0" rpy="0 0 0"/>
  </joint>

  <joint name="left_eye_joint" type="fixed">
    <parent link="head"/>
    <child link="left_eye"/>
    <origin xyz="0.4 -0.22 0.15" rpy="0 0 0"/>
  </joint>

  <joint name="right_eye_joint" type="fixed">
    <parent link="head"/>
    <child link="right_eye"/>
    <origin xyz="0.4 0.22 0.15" rpy="0 0 0"/>
  </joint>

  <joint name="mouth_joint" type="fixed">
    <parent link="head"/>
    <child link="mouth"/>
    <origin xyz="0.24 0 -0.2" rpy="0 0.7 0"/>
  </joint>
  
  <joint name="left_ear_joint" type="fixed">
    <parent link="head"/>
    <child link="left_ear"/>
    <origin xyz="0 -0.5 0" rpy="0 1.57 -1.0"/>
  </joint>

  <joint name="right_ear_joint" type="fixed">
    <parent link="head"/>
    <child link="right_ear"/>
    <origin xyz="0 0.5 0" rpy="0 1.57 1.0"/>
  </joint>

  <joint name="left_eyebrow_joint" type="fixed">
    <parent link="head"/>
    <child link="left_eyebrow"/>
    <origin xyz="0.39 -0.2 0.25" rpy="1.57 0 1.1"/>
  </joint>

  <joint name="right_eyebrow_joint" type="fixed">
    <parent link="head"/>
    <child link="right_eyebrow"/>
    <origin xyz="0.39 0.2 0.25" rpy="1.57 0.4 -1.1"/>
  </joint>

  
  <!-- Robot Base -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <xacro:box_inertia m="15" w="${base_width}" d="${base_length}" h="${base_height}"/>

  </link>
  
  <joint name="clown_head_joint" type="fixed">
    <parent link="base_link"/>
    <child link="head"/>
    <origin xyz="0 0 ${base_height/2 + 0.45}" rpy="0 0 0"/>
  </joint>
  
  <!-- Robot Footprint -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
  </joint>

    <!-- Wheels -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>

      <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}"/>

    </link>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel prefix="drivewhl_l" x_reflect="-1" y_reflect="1" />
  <xacro:wheel prefix="drivewhl_r" x_reflect="-1" y_reflect="-1" />

  <!-- Caster Wheel -->
  <link name="front_caster">
    <visual>
      <geometry>
        <sphere radius="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
      </geometry>
    </collision>

    <xacro:sphere_inertia m="0.5" r="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
  </link>

  <joint name="caster_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_caster"/>
    <origin xyz="${caster_xoff} 0.0 ${-(base_height/2)}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
  </joint>

</robot>
